version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:

    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Maven Test and generate coverage report
          command: mvn test
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -fsSL https://codecov.io/bash)

workflows:
  version: 2
  complete-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master